name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install_dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: run_pytest
        run: pytest

  diff_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run tests and generate coverage XML
        run: |
          pytest --cov=colslaue_etl --cov-report=xml:coverage.xml
      - name: Run diff-cover and check for new uncovered lines
        run: |
          diff-cover coverage.xml --fail-under=100 --diff-against origin/${{ github.base_ref }}
