name: tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pytest:
    runs-on: ubuntu-latest

    env:
      ENV: DEV

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install poetry
        run: pip install poetry

      - name: configure poetry
        run: poetry config virtualenvs.in-project true

      - name: install dependencies
        run: poetry install

      - name: run_pytest
        run: poetry run pytest

  diff_coverage:
    runs-on: ubuntu-latest

    env:
      ENV: DEV

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install poetry
        run: pip install poetry

      - name: configure poetry
        run: poetry config virtualenvs.in-project true

      - name: install dependencies
        run: poetry install

      - name: Run tests and generate coverage XML
        run: |
          poetry run pytest --cov=. tests/ --cov-report=xml:coverage.xml

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Run diff-cover and check for new uncovered lines
        run: |
          poetry run diff-cover coverage.xml --fail-under=100 --compare-branch origin/${{ github.base_ref }}

  lint:
    runs-on: ubuntu-latest

    env:
      ENV: DEV

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install poetry
        run: pip install poetry

      - name: configure poetry
        run: poetry config virtualenvs.in-project true

      - name: install dependencies
        run: poetry install

      - name: lint
        run: |
          poetry run black . --check

  build_image:
    needs: [run_pytest, diff_coverage, lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build_image
        run: |
          docker build --no-cache -t colslaue_etl:latest .
